runtime: nodejs
env: flex
beta_settings:
  cloud_sql_instances: portfolio-291707:us-central1:portfolio
env_variables:
  DB_USER: root
  DB_PASS: password
  DB_NAME: customers_db
  DB_SOCKET: /cloudsql/portfolio-291707:us-central1:portfolio